
server:
  port: 8888

logging:
  level:
    root: info

spring:
  security:
    basic:
      enabled: true
    user:
      name: user
      password: user123

fileserver:
   home: /data/fileserver/

